<a href="https://colab.research.google.com/github/shalini2705/DataAnalysis-Project-1/blob/main/AutomatedEDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
pip install dtale

Requirement already satisfied: dtale in /usr/local/lib/python3.13/dist-packages (3.22.0)
Requirement already satisfied: lz4 in /usr/local/lib/python3.13/dist-packages (from dtale) (4.4.5)
Requirement already satisfied: beautifulsoup4!=4.13.0b2 in /usr/local/lib/python3.13/dist-packages (from dtale) (4.13.5)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from dtale) (2026.7.22)
Requirement already satisfied: cycler in /usr/local/lib/python3.13/dist-packages (from dtale) (0.12.1)
Requirement already satisfied: dash in /usr/local/lib/python3.13/dist-packages (from dtale) (4.4.1)
Requirement already satisfied: dash-bootstrap-components in /usr/local/lib/python3.13/dist-packages (from dtale) (2.0.4)
Requirement already satisfied: et_xmlfile in /usr/local/lib/python3.13/dist-packages (from dtale) (2.0.0)
Requirement already satisfied: Flask in /usr/local/lib/python3.13/dist-packages (from dtale) (3.1.3)
Requirement already satisfied: Flask-Compress in /usr/local/lib/python3.13/dist-packages (from dtale) (1.25)
Requirement already satisfied: future>=0.14.0 in /usr/local/lib/python3.13/dist-packages (from dtale) (1.0.0)
Requirement already satisfied: itsdangerous in /usr/local/lib/python3.13/dist-packages (from dtale) (2.2.0)
Requirement already satisfied: kaleido in /usr/local/lib/python3.13/dist-packages (from dtale) (1.4.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (from dtale) (3.10.0)
Requirement already satisfied: missingno in /usr/local/lib/python3.13/dist-packages (from dtale) (0.5.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.13/dist-packages (from dtale) (3.6.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from dtale) (2.1.3)
Requirement already satisfied: openpyxl!=3.2.0b1 in /usr/local/lib/python3.13/dist-packages (from dtale) (3.1.5)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from dtale) (26.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from dtale) (2.2.3)
Requirement already satisfied: pkginfo in /usr/local/lib/python3.13/dist-packages (from dtale) (1.13)
Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (from dtale) (5.24.1)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from dtale) (2.32.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (from dtale) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from dtale) (1.16.3)
Requirement already satisfied: seaborn in /usr/local/lib/python3.13/dist-packages (from dtale) (0.13.2)
Requirement already satisfied: squarify in /usr/local/lib/python3.13/dist-packages (from dtale) (0.4.5)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.13/dist-packages (from dtale) (0.15.0)
Requirement already satisfied: strsimpy in /usr/local/lib/python3.13/dist-packages (from dtale) (0.2.1)
Requirement already satisfied: six in /usr/local/lib/python3.13/dist-packages (from dtale) (1.17.0)
Requirement already satisfied: werkzeug in /usr/local/lib/python3.13/dist-packages (from dtale) (3.1.8)
Requirement already satisfied: xarray in /usr/local/lib/python3.13/dist-packages (from dtale) (2025.12.0)
Requirement already satisfied: xlrd in /usr/local/lib/python3.13/dist-packages (from dtale) (2.0.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4!=4.13.0b2->dtale) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4!=4.13.0b2->dtale) (4.16.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.13/dist-packages (from dash->dtale) (9.0.1)
Requirement already satisfied: retrying in /usr/local/lib/python3.13/dist-packages (from dash->dtale) (1.4.2)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.13/dist-packages (from dash->dtale) (1.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.13/dist-packages (from dash->dtale) (80.10.2)
Requirement already satisfied: janus>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from dash->dtale) (2.0.0)
Requirement already satisfied: pydantic>=2.10 in /usr/local/lib/python3.13/dist-packages (from dash->dtale) (2.13.5)
Requirement already satisfied: comm in /usr/local/lib/python3.13/dist-packages (from dash->dtale) (0.2.3)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.13/dist-packages (from Flask->dtale) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.13/dist-packages (from Flask->dtale) (8.5.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.13/dist-packages (from Flask->dtale) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.13/dist-packages (from Flask->dtale) (3.0.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly->dtale) (9.1.4)
Requirement already satisfied: brotli in /usr/local/lib/python3.13/dist-packages (from Flask-Compress->dtale) (1.2.0)
Requirement already satisfied: backports.zstd in /usr/local/lib/python3.13/dist-packages (from Flask-Compress->dtale) (1.7.0)
Requirement already satisfied: choreographer>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from kaleido->dtale) (1.4.0)
Requirement already satisfied: logistro>=1.0.8 in /usr/local/lib/python3.13/dist-packages (from kaleido->dtale) (2.0.1)
Requirement already satisfied: orjson>=3.10.15 in /usr/local/lib/python3.13/dist-packages (from kaleido->dtale) (3.12.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dtale) (1.4.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dtale) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dtale) (1.5.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dtale) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dtale) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dtale) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->dtale) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->dtale) (2026.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->dtale) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->dtale) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->dtale) (2.5.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->dtale) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->dtale) (3.7.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels->dtale) (1.0.3)
Requirement already satisfied: formulaic>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from statsmodels->dtale) (1.2.2)
Requirement already satisfied: platformdirs>=4.3.6 in /usr/local/lib/python3.13/dist-packages (from choreographer>=1.3.0->kaleido->dtale) (4.11.8)
Requirement already satisfied: simplejson>=3.19.3 in /usr/local/lib/python3.13/dist-packages (from choreographer>=1.3.0->kaleido->dtale) (4.1.2)
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels->dtale) (2.0.1)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels->dtale) (2.26.0)
Requirement already satisfied: wrapt>=1.17.0rc1 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels->dtale) (2.4.1)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn->dtale) (3.1.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.10->dash->dtale) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.10->dash->dtale) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.10->dash->dtale) (0.4.4)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.13/dist-packages (from importlib-metadata->dash->dtale) (4.1.0)

In [24]:
#tools for auotmated EDA operations
import pandas as pd
import dtale
data=pd.read_csv("adult.csv")
dtale.show(data)

http://a4df6ba4c2d4:40000/dtale/main/2

In [25]:
pip install ydata-profiling

Requirement already satisfied: ydata-profiling in /usr/local/lib/python3.13/dist-packages (4.18.4)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (2.2.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (2.13.5)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /usr/local/lib/python3.13/dist-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (2.1.3)
Requirement already satisfied: minify-html>=0.15.0 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (0.15.0)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (4.6.0)
Requirement already satisfied: imagehash==4.3.2 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (0.61.2)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.13/dist-packages (from imagehash==4.3.2->ydata-profiling) (1.10.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.13/dist-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.3)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /usr/local/lib/python3.13/dist-packages (from numba<0.63,>=0.60->ydata-profiling) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2026.4)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.13/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->ydata-profiling) (2.46.5)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->ydata-profiling) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.7.22)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.3)
Requirement already satisfied: formulaic>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.2.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.13/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.13/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Requirement already satisfied: puremagic in /usr/local/lib/python3.13/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (2.2.0)
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels<1,>=0.13.2->ydata-profiling) (2.0.1)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels<1,>=0.13.2->ydata-profiling) (2.26.0)
Requirement already satisfied: wrapt>=1.17.0rc1 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels<1,>=0.13.2->ydata-profiling) (2.4.1)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=0.14.1->phik<0.13,>=0.12.5->ydata-profiling) (3.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)

In [26]:
import pandas as pd
from ydata_profiling import ProfileReport
data=pd.read_csv("adult.csv")
profile=ProfileReport(data,title=" Adult Dataset Report")
profile.to_notebook_iframe()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]
 13%|█▎        | 2/15 [00:00<00:01,  8.51it/s]
 27%|██▋       | 4/15 [00:00<00:01,  6.19it/s]
 47%|████▋     | 7/15 [00:00<00:00,  8.45it/s]
 60%|██████    | 9/15 [00:01<00:00,  7.68it/s]
 87%|████████▋ | 13/15 [00:01<00:00, 11.47it/s]
100%|██████████| 15/15 [00:01<00:00, 10.00it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [27]:
#automatic tool for visualization
!pip install autoviz

Requirement already satisfied: autoviz in /usr/local/lib/python3.13/dist-packages (0.1.905)
Requirement already satisfied: xlrd in /usr/local/lib/python3.13/dist-packages (from autoviz) (2.0.2)
Requirement already satisfied: wordcloud in /usr/local/lib/python3.13/dist-packages (from autoviz) (1.9.6)
Requirement already satisfied: emoji in /usr/local/lib/python3.13/dist-packages (from autoviz) (2.16.0)
Requirement already satisfied: pyamg in /usr/local/lib/python3.13/dist-packages (from autoviz) (5.3.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (from autoviz) (1.6.1)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.13/dist-packages (from autoviz) (0.15.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.13/dist-packages (from autoviz) (3.9.1)
Requirement already satisfied: textblob in /usr/local/lib/python3.13/dist-packages (from autoviz) (0.19.0)
Requirement already satisfied: xgboost<1.7,>=0.82 in /usr/local/lib/python3.13/dist-packages (from autoviz) (1.6.2)
Requirement already satisfied: fsspec>=0.8.3 in /usr/local/lib/python3.13/dist-packages (from autoviz) (2025.12.0)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.13/dist-packages (from autoviz) (4.16.0)
Requirement already satisfied: pandas-dq>=1.29 in /usr/local/lib/python3.13/dist-packages (from autoviz) (1.29)
Requirement already satisfied: numpy>=1.24.0 in /usr/local/lib/python3.13/dist-packages (from autoviz) (2.1.3)
Requirement already satisfied: hvplot>=0.9.2 in /usr/local/lib/python3.13/dist-packages (from autoviz) (0.12.2)
Requirement already satisfied: holoviews>=1.16.0 in /usr/local/lib/python3.13/dist-packages (from autoviz) (1.23.2)
Requirement already satisfied: panel>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from autoviz) (1.9.4)
Requirement already satisfied: pandas>=2.0 in /usr/local/lib/python3.13/dist-packages (from autoviz) (2.2.3)
Requirement already satisfied: matplotlib>3.7.4 in /usr/local/lib/python3.13/dist-packages (from autoviz) (3.10.0)
Requirement already satisfied: seaborn>0.12.2 in /usr/local/lib/python3.13/dist-packages (from autoviz) (0.13.2)
Requirement already satisfied: bokeh>=3.1 in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.16.0->autoviz) (3.8.2)
Requirement already satisfied: colorcet in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.16.0->autoviz) (3.2.1)
Requirement already satisfied: narwhals>=2 in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.16.0->autoviz) (2.26.0)
Requirement already satisfied: param<3.0,>=2.0 in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.16.0->autoviz) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.16.0->autoviz) (2.9.0.post0)
Requirement already satisfied: pyviz-comms>=2.1 in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.16.0->autoviz) (3.0.6)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from hvplot>=0.9.2->autoviz) (26.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>3.7.4->autoviz) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>3.7.4->autoviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>3.7.4->autoviz) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>3.7.4->autoviz) (1.5.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib>3.7.4->autoviz) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>3.7.4->autoviz) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.0->autoviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.0->autoviz) (2026.4)
Requirement already satisfied: linkify-it-py in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->autoviz) (2.2.0)
Requirement already satisfied: markdown in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->autoviz) (3.10.3)
Requirement already satisfied: markdown-it-py in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->autoviz) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->autoviz) (0.6.1)
Requirement already satisfied: nh3 in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->autoviz) (0.3.7)
Requirement already satisfied: panel-material-ui>=0.10.0 in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->autoviz) (0.14.2)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->autoviz) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->autoviz) (4.67.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->autoviz) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->autoviz) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->autoviz) (3.7.0)
Requirement already satisfied: click in /usr/local/lib/python3.13/dist-packages (from nltk->autoviz) (8.5.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.13/dist-packages (from nltk->autoviz) (2025.11.3)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels->autoviz) (1.0.3)
Requirement already satisfied: formulaic>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from statsmodels->autoviz) (1.2.2)
Requirement already satisfied: Jinja2>=2.9 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (3.1.6)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (6.0.3)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (6.5.7)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (2026.9.1)
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels->autoviz) (2.0.1)
Requirement already satisfied: wrapt>=1.17.0rc1 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels->autoviz) (2.4.1)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn->autoviz) (3.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->holoviews>=1.16.0->autoviz) (1.17.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py->panel>=1.4.0->autoviz) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->panel>=1.4.0->autoviz) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->panel>=1.4.0->autoviz) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->panel>=1.4.0->autoviz) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->panel>=1.4.0->autoviz) (2026.7.22)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from Jinja2>=2.9->bokeh>=3.1->holoviews>=1.16.0->autoviz) (3.0.3)

In [28]:
import pandas as pd
from autoviz.AutoViz_Class import AutoViz_Class
AV=AutoViz_Class()
data=pd.read_csv("adult.csv")
AV.AutoViz(
    filename="adult.csv",
    sep=",",
    depVar="Income",
    dfte=data)

Shape of your Data Set loaded: (32561, 15)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  0
    Number of Integer-Categorical Columns =  6
    Number of String-Categorical Columns =  7
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  1
    Number of Numeric-Boolean Columns =  0
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  0
    Number of Columns to Delete =  0
    14 Predictors classified...
        No variables removed since no ID or low-information variables found in data set

################ Binary_Classification problem #####################
To fix these data quality issues in the dataset, import FixDQ from autoviz...
There are 24 duplicate rows in your dataset
    Alert: Dropping duplicate rows can sometimes cause your column data types to change to object!
    All variables classified into correct types.

Total Number of Scatter Plots = 21
All Plots done
Time to run AutoViz = 20 seconds

 ###################### AUTO VISUALIZATION Completed ########################

,Age,Workclass,Final Weight,Education,EducationNum,Marital Status,Occupation,Relationship,Race,Gender,Capital Gain,capital loss,Hours per Week,Native Country,Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,0
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,1
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,0
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,0
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,1

In [29]:
pip install sweetviz

Requirement already satisfied: sweetviz in /usr/local/lib/python3.13/dist-packages (2.3.3)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (2.2.3)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (2.1.3)
Requirement already satisfied: matplotlib>=3.1.3 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (3.10.0)
Requirement already satisfied: tqdm>=4.43.0 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (4.67.3)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (1.16.3)
Requirement already satisfied: jinja2>=2.11.1 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (3.1.6)
Requirement already satisfied: importlib_resources>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2>=2.11.1->sweetviz) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)

In [30]:
import pandas as pd
import sweetviz as sv
data=pd.read_csv("adult.csv")
report=sv.analyze(data)
report.show_html("swwetviz_report.html")

                                             |          | [  0%]   00:00 -> (? left)

Report swwetviz_report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.